package cscie97.asn3.housemate.controller;

public enum ConfigItemType {

	CONFIG_ITEM_TYPE_ROOM, CONFIG_ITEM_TYPE_HOUSE, CONFIG_ITEM_TYPE_DEVICE, CONFIG_ITEM_TYPE_OCCUPANT, CONFIG_ITEM_TYPE_FEATURE, CONFIG_ITEM_ALL;

}
